[config]
type = "pipeline"
chartbook_format_version = "0.0.6"

[site]
title = "Garbuzov & Mitchell Replication Project"
author = "Garbuzov & Mitchell"
copyright = "2026"
logo_path = ""
favicon_path = ""

[pipeline]
id = "MYPROJ"
pipeline_name = "Garbuzov & Mitchell Replication"
pipeline_description = "Commodities replication chartbook"
lead_pipeline_developer = "Garbuzov & Mitchell"
contributors = ["Daniil Garbuzov", "Oliver Mitchell"]
runs_on_grid_or_windows_or_other = "Windows/Linux/MacOS"
git_repo_URL = "https://github.com/daniilygarbuzov/p16_Garbuzov_Mitchell_2026"
README_file_path = "./README.md"

[notebooks]

###FRED INFO
#chart
[charts.treasury_yields]
chart_name = "Treasury Yields"
short_description_chart = "Treasury yields over time"
dataframe_id = "treasury_yields"
path_to_html_chart = "./p16_slug/_output/treasury_yields.html"
chart_docs_path = "./p16_slug/docs_src/charts/treasury_yields.md"


#dataframe
[dataframes.treasury_yields]
dataframe_name = "Treasury Yields"
short_description_df = "Treasury yields over time"
data_sources = ["FRED"]
data_providers = ["FRED"]
how_is_pulled = "FRED API via Python"
path_to_parquet_data = "./p16_slug/_data/fred.parquet"
dataframe_docs_path = "./p16_slug/docs_src/dataframes/fred.md"
date_col = "DATE"

###WRDS INFO
#chart
[charts.futures_settlements]
chart_name = "Futures settlements"
short_description_chart = "Commodities futures settlement prices"
dataframe_id = "futures_settlements"
path_to_html_chart = "./p16_slug/_output/futures_settlements.html"
chart_docs_path = "./p16_slug/docs_src/charts/futures_settlements.md"


#dataframe
[dataframes.futures_settlements]
dataframe_name = "Futures settlements"
short_description_df = "Settlements for futures contracts over time and diff. commodities"
data_sources = ["LSEG via WRDS"]
data_providers = ["WRDS"]
how_is_pulled = "API query via Python"
path_to_parquet_data = "./p16_slug/_data/wrds_futures.parquet"
dataframe_docs_path = "./p16_slug/docs_src/dataframes/wrds.md"
date_col = "date"